import type { BallConfig, SlotSymbolId } from "@/game/types";

export const BALL_CONFIG_BY_SYMBOL: Record<SlotSymbolId, BallConfig> = {
  "1": {
    symbol: "1",
    colorName: "白",
    ability: "none",
    bounces: 2,
    speed: 360,
    radius: 7,
    fill: "#f8fafc",
    stroke: "#94a3b8",
  },
  "2": {
    symbol: "2",
    colorName: "赤",
    ability: "penetrate",
    bounces: 2,
    speed: 370,
    radius: 7,
    fill: "#ef4444",
    stroke: "#991b1b",
  },
  "3": {
    symbol: "3",
    colorName: "オレンジ",
    ability: "explode",
    bounces: 2,
    speed: 365,
    radius: 8,
    fill: "#fb923c",
    stroke: "#c2410c",
  },
  "4": {
    symbol: "4",
    colorName: "黄",
    ability: "wallPass",
    bounces: 2,
    speed: 360,
    radius: 7,
    fill: "#facc15",
    stroke: "#a16207",
  },
  "5": {
    symbol: "5",
    colorName: "緑",
    ability: "doubleMedal",
    bounces: 2,
    speed: 360,
    radius: 7,
    fill: "#22c55e",
    stroke: "#166534",
  },
  "6": {
    symbol: "6",
    colorName: "青",
    ability: "extraBounce",
    bounces: 4,
    speed: 375,
    radius: 7,
    fill: "#38bdf8",
    stroke: "#075985",
  },
  "7": {
    symbol: "7",
    colorName: "虹",
    ability: "rainbow",
    bounces: 5,
    speed: 390,
    radius: 8,
    fill: "url(#rainbowBall)",
    stroke: "#7c3aed",
  },
};